# Generated by Django 4.1.4 on 2023-05-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_slug_alter_producttag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
