# Generated by Django 4.1.4 on 2023-05-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_producttag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
