# Generated by Django 4.1.4 on 2023-05-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_stock_alter_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
