# Generated by Django 4.1.4 on 2023-06-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
