# Generated by Django 4.1.4 on 2023-06-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_blog_image_alter_slider_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='FAQs',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='phone',
        ),
    ]
