# Generated by Django 4.1.4 on 2023-06-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_delete_blog_delete_faqs_delete_slider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteSetting',
        ),
    ]
