# Generated by Django 4.1.4 on 2023-06-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_cover_image'),
        ('cart', '0002_cart_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation'),
        ),
    ]
